modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="k7a2_fools"
version="1.5.6.2"
displayName="k7a2_fools"
displayURL="https://phucdh0110.localplayer.dev"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="DHPhuc"
description="A FOSS Version of K7A2 Fools"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.k7a2_fools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration